In [33]:
import numpy as np

a = np.array([[[1,2,3],[8,9,9],[8,10,11],[7,8,9],[3,4,1]],[[5,7,8],[2,2,2],[7,5,6],[9,9,9],[1,1,1]],[[5,7,8],[2,2,2],[4,4,4],[0,5,4],[10,4,5]],[[5,7,8],[2,2,2],[4,4,4],[8,8,8],[9,5,6]]])
print(a)
print(np.shape(a))

[[[ 1  2  3]
  [ 8  9  9]
  [ 8 10 11]
  [ 7  8  9]
  [ 3  4  1]]

 [[ 5  7  8]
  [ 2  2  2]
  [ 7  5  6]
  [ 9  9  9]
  [ 1  1  1]]

 [[ 5  7  8]
  [ 2  2  2]
  [ 4  4  4]
  [ 0  5  4]
  [10  4  5]]

 [[ 5  7  8]
  [ 2  2  2]
  [ 4  4  4]
  [ 8  8  8]
  [ 9  5  6]]]
(4, 5, 3)


In [34]:
b = np.transpose(a,(2,0,1))
print(b)
print(np.shape(b))

[[[ 1  8  8  7  3]
  [ 5  2  7  9  1]
  [ 5  2  4  0 10]
  [ 5  2  4  8  9]]

 [[ 2  9 10  8  4]
  [ 7  2  5  9  1]
  [ 7  2  4  5  4]
  [ 7  2  4  8  5]]

 [[ 3  9 11  9  1]
  [ 8  2  6  9  1]
  [ 8  2  4  4  5]
  [ 8  2  4  8  6]]]
(3, 4, 5)


In [35]:
import torch
from torch import nn
from torchvision import transforms as T

b_copy = b.copy()
b_tensor = torch.tensor(b_copy, dtype = torch.float)
gray = T.Grayscale(num_output_channels = 1)
b_gray = gray(b_tensor)
print(b_gray)

tensor([[[1.8149, 8.7002, 9.5152, 7.8143, 3.3587],
         [6.5155, 1.9998, 5.7113, 8.9991, 0.9999],
         [6.5155, 1.9998, 3.9996, 3.3910, 5.9070],
         [6.5155, 1.9998, 3.9996, 7.9992, 6.3091]]])


In [36]:
resize = T.Resize((2,3))
b_resz = resize(b_gray)
print(b_resz)

tensor([[[4.5601, 7.6132, 4.2551],
         [5.0103, 3.9996, 5.9704]]])
